/*
Customize & Generate Page for AntarAalay.ai

Allows users to:
- View uploaded room images
- Select design style
- Customize wall color, flooring, furniture
- Generate AI designs
*/
import { useEffect, useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery, useMutation } from '@tanstack/react-query';
import { Sparkles, ArrowLeft, Loader2, Palette, Sofa, Grid3X3, Paintbrush } from 'lucide-react';
import { getRoom } from '../services/room';
import { generateDesign } from '../services/design';
import { logger } from '../utils/logger';

const DESIGN_STYLES = [
  { value: 'modern', label: 'Modern', description: 'Clean lines and contemporary aesthetics' },
  { value: 'traditional', label: 'Traditional Indian', description: 'Ethnic decor with warm tones' },
  { value: 'contemporary', label: 'Contemporary', description: 'Sleek and current trends' },
  { value: 'minimalist', label: 'Minimalist', description: 'Clutter-free simplicity' },
  { value: 'luxury', label: 'Luxury', description: 'Premium materials and elegance' },
];

const FURNITURE_STYLES = [
  { value: 'modern', label: 'Modern' },
  { value: 'vintage', label: 'Vintage' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'scandinavian', label: 'Scandinavian' },
  { value: 'bohemian', label: 'Bohemian' },
  { value: 'classic', label: 'Classic Indian' },
];

const FLOORING_OPTIONS = [
  { value: 'hardwood', label: 'Hardwood' },
  { value: 'marble', label: 'Marble' },
  { value: 'tiles', label: 'Ceramic Tiles' },
  { value: 'granite', label: 'Granite' },
  { value: 'vinyl', label: 'Vinyl' },
  { value: 'carpet', label: 'Carpet' },
];

const WALL_COLORS = [
  { value: 'warm beige', label: 'Warm Beige', class: 'bg-[#D4A574]' },
  { value: 'soft white', label: 'Soft White', class: 'bg-[#F5F5DC]' },
  { value: 'sage green', label: 'Sage Green', class: 'bg-[#9CAF88]' },
  { value: 'sky blue', label: 'Sky Blue', class: 'bg-[#87CEEB]' },
  { value: 'terracotta', label: 'Terracotta', class: 'bg-[#E2725B]' },
  { value: 'cream', label: 'Cream', class: 'bg-[#FFFDD0]' },
  { value: 'dusty rose', label: 'Dusty Rose', class: 'bg-[#DCAE96]' },
  { value: 'mint', label: 'Mint', class: 'bg-[#98FF98]' },
];

export default function Customize() {
  const { roomId } = useParams<{ roomId: string }>();
  const navigate = useNavigate();
  const hasAutoGenerated = useRef(false);
  
  const [style, setStyle] = useState('modern');
  const [wallColor, setWallColor] = useState('warm beige');
  const [flooring, setFlooring] = useState('hardwood');
  const [furnitureStyle, setFurnitureStyle] = useState('modern');
  
  // Fetch room data
  const { data: room, isLoading: roomLoading } = useQuery({
    queryKey: ['room', roomId],
    queryFn: () => getRoom(roomId!),
    enabled: !!roomId,
  });
  
  // Generate design mutation
  const generateMutation = useMutation({
    mutationFn: () => generateDesign({
      room_id: roomId!,
      style,
    }),
    onSuccess: (data) => {
      logger.info('Design generated', { designId: data.design_id });
      navigate(`/designs/${roomId}`);
    },
    onError: (error) => {
      logger.error('Design generation failed', {}, error as Error);
    },
  });

  useEffect(() => {
    if (!roomId) return;
    if (roomLoading) return;
    if (generateMutation.isPending) return;
    if (hasAutoGenerated.current) return;
    if (!room) return;

    hasAutoGenerated.current = true;
    generateMutation.mutate();
  }, [roomId, roomLoading, room, generateMutation]);
  
  if (roomLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-rose-50 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 animate-spin text-amber-600 mx-auto mb-4" />
          <p className="text-amber-700">Loading room...</p>
        </div>
      </div>
    );
  }
  
  return (
    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-rose-50">
      {/* Header */}
      <header className="w-full px-6 py-4 bg-white/70 backdrop-blur-md border-b border-amber-100">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2">
            <button
              onClick={() => navigate(-1)}
              className="p-2 hover:bg-amber-100 rounded-lg text-amber-700"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="w-10 h-10 bg-amber-600 rounded-xl flex items-center justify-center">
              <Palette className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-2xl font-bold text-amber-900">Customize Design</h1>
          </div>
        </div>
      </header>
      
      <main className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-2 gap-8">
          {/* Left Panel - Room Preview */}
          <div className="space-y-6">
            <div className="bg-white/80 rounded-2xl p-6 border border-amber-100">
              <h2 className="text-lg font-semibold text-amber-950 mb-4">Room Photos</h2>
              
              {room?.images && (
                <div className="grid grid-cols-2 gap-3">
                  {Object.entries(room.images).map(([direction, url]) => (
                    <div key={direction} className="relative aspect-square rounded-xl overflow-hidden">
                      <img
                        src={url as string}
                        alt={direction}
                        className="w-full h-full object-cover"
                      />
                      <div className="absolute bottom-2 left-2 px-2 py-1 bg-black/50 text-white text-xs rounded capitalize">
                        {direction}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
            
            {/* Tips */}
            <div className="bg-amber-50 rounded-xl p-4 border border-amber-200">
              <h3 className="text-sm font-medium text-amber-800 mb-2">Design Tips:</h3>
              <ul className="text-sm text-amber-600 space-y-1">
                <li>• Choose colors that complement your furniture</li>
                <li>• Consider lighting when selecting wall colors</li>
                <li>• Match flooring to your lifestyle needs</li>
              </ul>
            </div>
          </div>
          
          {/* Right Panel - Customization */}
          <div className="space-y-6">
            {/* Style Selection */}
            <div className="bg-white/80 rounded-2xl p-6 border border-amber-100">
              <h2 className="text-lg font-semibold text-amber-950 mb-4 flex items-center gap-2">
                <Grid3X3 className="w-5 h-5 text-amber-600" />
                Design Style
              </h2>
              
              <div className="grid grid-cols-2 gap-3">
                {DESIGN_STYLES.map((s) => (
                  <button
                    key={s.value}
                    onClick={() => setStyle(s.value)}
                    className={`p-3 rounded-xl border-2 text-left transition-all ${
                      style === s.value
                        ? 'border-amber-500 bg-amber-50'
                        : 'border-amber-200 hover:border-amber-300'
                    }`}
                  >
                    <span className="font-medium text-amber-900 block">{s.label}</span>
                    <span className="text-xs text-amber-600">{s.description}</span>
                  </button>
                ))}
              </div>
            </div>
            
            {/* Wall Color */}
            <div className="bg-white/80 rounded-2xl p-6 border border-amber-100">
              <h2 className="text-lg font-semibold text-amber-950 mb-4 flex items-center gap-2">
                <Paintbrush className="w-5 h-5 text-amber-600" />
                Wall Color
              </h2>
              
              <div className="grid grid-cols-4 gap-3">
                {WALL_COLORS.map((color) => (
                  <button
                    key={color.value}
                    onClick={() => setWallColor(color.value)}
                    className={`relative aspect-square rounded-xl border-2 transition-all ${
                      wallColor === color.value
                        ? 'border-amber-500 scale-105'
                        : 'border-transparent hover:scale-105'
                    }`}
                  >
                    <div className={`w-full h-full rounded-lg ${color.class}`} />
                    {wallColor === color.value && (
                      <div className="absolute inset-0 flex items-center justify-center">
                        <div className="w-6 h-6 bg-white rounded-full flex items-center justify-center">
                          <svg className="w-4 h-4 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                          </svg>
                        </div>
                      </div>
                    )}
                    <span className="text-xs text-amber-800 mt-1 block text-center truncate">
                      {color.label}
                    </span>
                  </button>
                ))}
              </div>
            </div>
            
            {/* Flooring */}
            <div className="bg-white/80 rounded-2xl p-6 border border-amber-100">
              <h2 className="text-lg font-semibold text-amber-950 mb-4">Flooring</h2>
              
              <div className="grid grid-cols-3 gap-3">
                {FLOORING_OPTIONS.map((f) => (
                  <button
                    key={f.value}
                    onClick={() => setFlooring(f.value)}
                    className={`p-3 rounded-xl border-2 text-center transition-all ${
                      flooring === f.value
                        ? 'border-amber-500 bg-amber-50'
                        : 'border-amber-200 hover:border-amber-300'
                    }`}
                  >
                    <span className="font-medium text-amber-900">{f.label}</span>
                  </button>
                ))}
              </div>
            </div>
            
            {/* Furniture Style */}
            <div className="bg-white/80 rounded-2xl p-6 border border-amber-100">
              <h2 className="text-lg font-semibold text-amber-950 mb-4 flex items-center gap-2">
                <Sofa className="w-5 h-5 text-amber-600" />
                Furniture Style
              </h2>
              
              <div className="grid grid-cols-3 gap-3">
                {FURNITURE_STYLES.map((f) => (
                  <button
                    key={f.value}
                    onClick={() => setFurnitureStyle(f.value)}
                    className={`p-3 rounded-xl border-2 text-center transition-all ${
                      furnitureStyle === f.value
                        ? 'border-amber-500 bg-amber-50'
                        : 'border-amber-200 hover:border-amber-300'
                    }`}
                  >
                    <span className="font-medium text-amber-900">{f.label}</span>
                  </button>
                ))}
              </div>
            </div>
            
            {/* Generate Button */}
            <button
              onClick={() => generateMutation.mutate()}
              disabled={generateMutation.isPending}
              className="w-full flex items-center justify-center gap-2 px-6 py-4 bg-amber-600 hover:bg-amber-700 disabled:bg-amber-300 text-white rounded-xl font-semibold transition-all"
            >
              {generateMutation.isPending ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating AI Designs...
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5" />
                  Generate AI Designs
                </>
              )}
            </button>
            
            {generateMutation.isError && (
              <p className="text-red-600 text-sm text-center">
                Generation failed. Please try again.
              </p>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
